creator:
  build: .
  dockerfile: Dockerfile-server
  ports:
   - 80:3000
  environment:
    DEPLOYED: "true"
  links:
   - redis
   - postgres

solution:
  build: .
  dockerfile: Dockerfile-worker
  environment:
    DEPLOYED: "true"
  links:
   - redis
   - postgres

redis:
  image: redis

postgres:
  image: postgres